### ISSUE TITLE
大佬，cookie过期不会通知，不会自动禁用

### ISSUE THREAD

**Issue by Yvan0329** [langhun/xdd#1]
大佬，cookie过期不会通知，不会自动禁用

**Comment by langhun** [comment]
> 大佬，cookie过期不会通知，不会自动禁用

你找错地方了吧

**Comment by langhun** [comment]
> 大佬，cookie过期不会通知，不会自动禁用

去这里找大佬
https://github.com/764763903a/xdd-plus

**Comment by langhun** [comment]
我还是没明白，你是怎么找到我库来的

Yvan0329 ***@***.***> 于2021年9月18日周六 上午1:35写道：
